version: "3.9"  # optional since v1.27.0
services:
  vue:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: cart
    volumes:
      - ./:/usr/src/app/app
      - /usr/src/app/app/node_modules